import {
  assertHasAllKeys,
  type BaseColorKey,
  type DerivedColorKey,
  THEME_ADVANCED_COLOR_KEYS,
  type ThemeColors,
  type ThemePreset,
} from "./themeColorDefinitions";
import { DERIVED_COLOR_REFS } from "./themeDerivations";

type ThemeBaseColors = ThemeColors & Required<Pick<ThemeColors, BaseColorKey>>;
type CompleteThemeColors = Required<ThemeColors>;

function completeTheme(colors: ThemeBaseColors): CompleteThemeColors {
  const complete: Partial<Record<DerivedColorKey, string>> & ThemeBaseColors = { ...colors };
  for (const key of THEME_ADVANCED_COLOR_KEYS) complete[key] ??= DERIVED_COLOR_REFS[key];
  assertHasAllKeys(complete, THEME_ADVANCED_COLOR_KEYS);
  return complete;
}

const DARK_THEME_BASE = {
  accent: "oklch(0.69 0.15 250)",
  accentHover: "@accent 6%L -2%C",
  badgeBg: "@danger -8%L 4%C",
  border: "@textSecondary 10%",
  borderStrong: "@textSecondary 18%",
  codeBg: "@mainBg -6%L -0.2%C 48%",
  composerBg: "@mainBg 3%L 0.1%C",
  danger: "oklch(0.74 0.13 25)",
  mainBg: "oklch(0.21 0.012 255)",
  mentionInaccessibleText: "@textDim 9%L",
  mentionText: "@accent 6%L -2%C",
  presenceActive: "oklch(0.66 0.14 155)",
  railBg: "@mainBg -2%L",
  sidebarBg: "@mainBg -4%L -0.1%C",
  textDim: "@textPrimary -37%L 0.4%C",
  textDisabled: "@textDim -9.5%L",
  textOnAccent: "oklch(0.17 0.011 255)",
  textOnAvatar: "@textPrimary 8%L",
  textPrimary: "oklch(0.89 0.006 255)",
  textSecondary: "@textPrimary -19%L 0.2%C",
  warning: "oklch(0.78 0.12 82)",
} satisfies ThemeColors;

const tintedTheme = (hue: number, accent: string, accentHover: string): ThemeColors =>
  completeTheme({
    ...DARK_THEME_BASE,
    accent,
    accentHover,
    composerBg: "@mainBg 3.5%L 0.2%C",
    mainBg: `oklch(0.18 0.014 ${hue})`,
    railBg: "@mainBg -3.5%L -0.2%C",
    sidebarBg: "@mainBg -7%L -0.4%C",
  });

const CHARCOAL_THEME_BASE = {
  accent: "oklch(0.62 0.19 260)",
  accentHover: "@accent 6%L -2%C",
  badgeBg: "@danger -8%L 4%C",
  border: "@textSecondary 10%",
  borderStrong: "@textSecondary 18%",
  codeBg: "@mainBg 4%L 48%",
  composerBg: "@mainBg 3%L",
  danger: "oklch(0.68 0.19 25)",
  mainBg: "oklch(0.08 0 0)",
  mentionInaccessibleText: "@textDim 9%L",
  mentionText: "@accent 6%L -2%C",
  presenceActive: "oklch(0.7 0.16 155)",
  railBg: "@mainBg",
  sidebarBg: "@mainBg",
  textDim: "@textPrimary -37%L",
  textDisabled: "@textDim -9.5%L",
  textOnAccent: "oklch(0.98 0 0)",
  textOnAvatar: "@textPrimary 8%L",
  textPrimary: "oklch(0.96 0 0)",
  textSecondary: "@textPrimary -35%L",
  warning: "oklch(0.8 0.14 82)",
} satisfies ThemeColors;

export const THEME_PRESETS: ThemePreset[] = [
  { colors: completeTheme(DARK_THEME_BASE), id: "dark", label: "Slate" },
  { colors: completeTheme(CHARCOAL_THEME_BASE), id: "charcoal", label: "Charcoal" },
  {
    colorScheme: "light",
    colors: completeTheme({
      ...DARK_THEME_BASE,
      accent: "oklch(0.56 0.15 250)",
      accentHover: "@accent -7%L",
      activeBg: "@accent 12%",
      badgeBg: "@danger",
      blockKitButtonDanger: "@badgeBg",
      blockKitButtonPrimary: "@presenceActive",
      border: "@textPrimary -2.5%L 10%",
      borderStrong: "@textPrimary -2.5%L 18%",
      codeBg: "@mainBg -88%L 0.6%C 6%",
      composerBg: "@mainBg 1%L -0.1%C",
      danger: "oklch(0.54 0.18 25)",
      embeddedContentBg: "@composerBg",
      hoverBg: "@border 5%",
      mainBg: "oklch(0.985 0.002 255)",
      mediaLensBorder: "@composerBg 88%",
      mentionText: "@accent -2%L",
      mentionInaccessibleText: "@textDim 5%L",
      userStatusOver18: "@warning",
      presenceActive: "oklch(0.52 0.14 155)",
      railBg: "@mainBg -3.5%L 0.2%C",
      sidebarBg: "@mainBg -2%L 0.1%C",
      success: "@presenceActive",
      textDim: "@textPrimary 30%L",
      textDisabled: "@textDim 10%L",
      textOnAccent: "oklch(0.985 0.002 255)",
      textOnAvatar: "@mainBg",
      textOnDanger: "@mainBg",
      textOnSuccess: "@mainBg",
      textPrimary: "oklch(0.2 0.01 255)",
      textSecondary: "@textPrimary 20%L 0.1%C",
      warning: "oklch(0.52 0.13 82)",
    }),
    id: "light",
    label: "Porcelain",
  },
  {
    colors: tintedTheme(310, "oklch(0.68 0.14 310)", "@accent 7%L -3%C"),
    id: "aubergine",
    label: "Aubergine",
  },
  {
    colors: tintedTheme(175, "oklch(0.69 0.12 175)", "@accent 8%L -2%C"),
    id: "forest",
    label: "Forest",
  },
  {
    colors: tintedTheme(350, "oklch(0.68 0.16 350)", "@accent 7%L -3%C"),
    id: "crimson",
    label: "Crimson",
  },
  {
    colors: tintedTheme(48, "oklch(0.7 0.15 48)", "@accent 8%L -3%C"),
    id: "sunset",
    label: "Sunset",
  },
  {
    colors: completeTheme({
      accent: "#cba6f7",
      accentHover: "#b4befe",
      activeBg: "@textPrimary 12%",
      badgeBg: "@danger",
      blockKitButtonDanger: "@badgeBg",
      blockKitButtonPrimary: "@presenceActive",
      border: "@textSecondary -41.3%L -0.8%C",
      borderStrong: "@textSecondary -34%L -0.6%C",
      codeBg: "@mainBg -7.5%L -1.3%C",
      composerBg: "@mainBg 8.1%L 0.2%C",
      danger: "#f38ba8",
      hoverBg: "@textPrimary 7%",
      mainBg: "#1e1e2e",
      mentionText: "#89b4fa",
      userStatusOver18: "@warning",
      presenceActive: "#a6e3a1",
      railBg: "@mainBg -6%L -1%C",
      sidebarBg: "@mainBg -2.7%L -0.5%C",
      success: "@presenceActive",
      textDim: "@textPrimary -32.9%L -0.9%C",
      textOnAccent: "#11111b",
      textPrimary: "#cdd6f4",
      textSecondary: "@textPrimary -6.2%L -0.3%C",
      warning: "#f9e2af",
    }),
    id: "catppuccin",
    label: "Catppuccin Mocha",
  },
  {
    colors: completeTheme({
      accent: "#d79921",
      accentHover: "#fabd2f",
      activeBg: "@textPrimary 12%",
      badgeBg: "@danger -11.4%L -1.5%C",
      blockKitButtonDanger: "@badgeBg",
      blockKitButtonPrimary: "@presenceActive",
      border: "@textSecondary -27.9%L -2.3%C",
      borderStrong: "@textSecondary -20.8%L -1.6%C",
      codeBg: "@mainBg -6%L 0.4%C",
      composerBg: "@mainBg 6.7%L 0.7%C",
      danger: "#fb4934",
      hoverBg: "@textPrimary 7%",
      mainBg: "#282828",
      mentionText: "#83a598",
      userStatusOver18: "@warning",
      presenceActive: "#b8bb26",
      railBg: "@mainBg -3.6%L 0.5%C",
      sidebarBg: "@mainBg 3.4%L 0.3%C",
      success: "@presenceActive",
      textDim: "@textPrimary -27.5%L -2.8%C",
      textOnAccent: "#1d2021",
      textPrimary: "#ebdbb2",
      textSecondary: "@textPrimary -20.4%L -2.2%C",
      warning: "#fabd2f",
    }),
    id: "gruvbox",
    label: "Gruvbox",
  },
  {
    colors: completeTheme({
      accent: "#88c0d0",
      accentHover: "#8fbcbb",
      activeBg: "@textPrimary 12%",
      badgeBg: "@danger",
      blockKitButtonDanger: "@badgeBg",
      blockKitButtonPrimary: "@presenceActive",
      border: "@textSecondary -48.4%L 1.6%C",
      borderStrong: "@textDim",
      codeBg: "@mainBg -7.4%L -0.7%C",
      composerBg: "@mainBg 3.1%L 0.3%C",
      danger: "#bf616a",
      hoverBg: "@textPrimary 7%",
      mainBg: "#2e3440",
      mentionText: "@accent",
      userStatusOver18: "@warning",
      presenceActive: "#a3be8c",
      railBg: "@mainBg -3.7%L -0.4%C",
      sidebarBg: "@mainBg 5.5%L 0.6%C",
      success: "@presenceActive",
      textDim: "@textPrimary -49.9%L 2.8%C",
      textOnAccent: "#2e3440",
      textPrimary: "#eceff4",
      textSecondary: "@textPrimary -5.2%L 0.9%C",
      warning: "#ebcb8b",
    }),
    id: "nord",
    label: "Nord",
  },
];
