export const SLACK_OPERATIONS = new Set([
  "activity.feed",
  "apps.actions.v2.execute",
  "apps.profile.get",
  "blocks.actions",
  "bots.info",
  "chat.command",
  "client.appCommands",
  "commands.list",
  "dnd.endSnooze",
  "dnd.setSnooze",
  "drafts.create",
  "drafts.delete",
  "drafts.list",
  "search.autocomplete",
  "search.messages",
  "search.modules.people",
  "team.profile.get",
  "usergroups.update",
  "usergroups.users.list",
  "usergroups.users.update",
  "users.prefs.set",
  "users.profile.set",
  "users.setPresence",
]);

export const SLACK_EDGE_OPERATIONS = new Set(["usergroups/info", "users/info"]);
